### PR TITLE
compiler-gcc: integrate the various compiler-gcc[345].h files

### PR DESCRIPTION
**Pull request by stefansaraev**
this is a cherry-pick from 3.14 stable tree (already in v3.14.69) 

http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?h=3711edaf01a01818f2aed9f21efe29b9818134b9

will be needed once LibreELEC switches to gcc6. but should also be fine with gcc4/5

EDIT: do not merge before compile tested with gcc 5 (or better, do not merge before LE switches to gcc6)

### CODE REVIEW

**Comment by lrusak** [comment]
we should look at this again

**Comment by stefansaraev** [comment]
should be safe. it's already in project specific patchdirs like https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/WeTek_Hub/patches/linux/linux-compiler-gcc.h.patch

**Comment by chewitt** [comment]
so if this is merged we can drop the project-specific patches? .. any objections?

**Comment by codesnake** [comment]
Yes, then we can drop project-specific patches.

**Pull request merged**
