### PR TITLE
Clean bump to Kernel 3.14.79

### PR DESCRIPTION
**Pull request by Stane1983**
I deleted previous PR because it wasn't clean (some commits are not supposed to be there).

### CODE REVIEW

**Comment by codesnake** [comment]
Anyway you left the commit that kills Hotplug governor here... Please look at another example - @stefansaraev rebased AML Marshmallow kernel on top of 3.14.79, but still keeps Hotplug governor: https://github.com/stefansaraev/linux/tree/amlogic-3.14.79

**Comment by stefansaraev** [comment]
it should be noted that my rebase has missing few linaro commins: 
- ~~~near~~~ eveything that had "config: " in commit msg (linaro/configs)
- everything that had "_kvm_" in commit msg
- tty backport from 4.3: https://github.com/codesnake/linux-amlogic/commit/40436644b0e7b2b2a0040c2189ca4a0f9943e75f (edit: referenced wrong commit - updated) <- I did not care to properly adjust this because it was a bit intrusive and there is zero benefit to LE imo. kvm and linaro config changes are irrelevant to LE, too.

besides that, every commit that had conflicts was tripplechecked and adapted to updstream 3.14 changes. but I can not guarantee that it will even compile (I am using a very minimal config) or be fine at runtime.

also I did not pick #3, I just rebased codenake's tree, and #3 was not yet merged to LibreELEC/linux-amlogic at that time.

EDIT: if you look deeper and find other commits missing, that's because changes are already pushed upstream. I dont remember the exact commits but there are at least 5 I had to skip

**Comment by Stane1983** [comment]
@stefansaraev your kernel compiles with hotplug governor but amlogic watchpoint driver throws error on building (missing declarations). Tested with meson64_defconfig (maybe some changes needed in Kconfigs).

My point would be that hotplug governor is not needed for Linux purposes and afaik it's not maintained for longer time. It doesn't exist in Linaro 3.14 or Android 3.14 kernel. And I have to apologize for saying that hotplug won't compile. I recall that I initially removed it because it was crashing kernel when switching from performance to hotplug governor. That's reason why I decided to ditch hotplug and use ondemand instead.

If you guys disagree with this or do not want this PR just reject it, what's big deal?

**Comment by stefansaraev** [comment]
I am not the one in position to approve or reject PRs here. I rebased just for fun. 

sure, as I said, no guarantee that it will compile for eveyone. 

I am testing with minimal config here. no PERF_EVENTS, so no AMLOGIC_WATCHPOINT, yes DBG_MDSCR_ move (https://github.com/codesnake/linux-amlogic/commit/ea9071dc8d6d73f65011782c4932d32373cad494) was yet another change I forgot to mention above, iirc because it was part of a quite big kvm merge, indeed skipping that commit obviously affects other things :)

https://github.com/stefansaraev/linux/commit/1ec6fbf6fc0dbee41a473041fdcfb60c33f43b5e this one should (EDIT: hopefuly.. not build and runtime tested...) fix watchpoint

**Comment by stefansaraev** [comment]
fyi, month or two ago, I tested kodi with (as is, not tuned at all) ondemand governor on wetek core, I have (not uncommon) use case where I need software decoding for some videos/live streams (in particular some mpeg-2 live tv channels). ondemand was doing way worse than hotplug. I think hotplug is a good thing and should stay.

wetek core is 3.10. things may have changed in 3.14, not tested on wetek play 2 yet. I'll do next few days..

**Comment by codesnake** [comment]
@Stane1983 Noone said your PR is bad, you did great work. Anyway I plan to switch WeTek LE projects to another scaling governor (most likely interactive), but I think it is worth to keep hotplug governor as an option, if possible.

**Comment by lrusak** [comment]
superseded by #19

**Pull request closed without merging**
