### PR TITLE
Add support for WeTek Hub IR remote to RC core

### PR DESCRIPTION
**Pull request by codesnake**
Add keymap and some accompanying fixes to make WeTek Hub IR remote work with RC core.

### CODE REVIEW

**Comment by Ray-future** [comment]
Nice, I will try to make a keymap for WP2 and C2 too.

**Comment by Kwiboo** [comment]
@Raybuntu see https://github.com/Kwiboo/linux-rockchip/compare/rockchip-4.4-ir%5E%5E%5E...rockchip-4.4-ir for C2 and WP2 keymap, the WP2 keymap might need some tweaking.

Also https://github.com/Kwiboo/LibreELEC.tv/commit/2960897025aadb0c7d6a6b97445fa39f51f962d7 has a patch that adds the ir-keytable friendly keymaps

**Comment by Ray-future** [comment]
thanks

**Comment by wrxtasy** [comment]
Used Kwiboo's Keymap for the ODROID C2 and a modded .dts and I have no issues with the Hardkernel C2 - NEC IR remote and this PR.

I will submit a seperate RC-core PR for the C2.

**Comment by codesnake** [comment]
Added a commit required to build kernel media support drivers as a modules (set CONFIG_MEDIA_SUPPORT=m). RC core loads keymap defined in device tree by rc-map-name only when itself is compiled as a module. Currently all AML-based projects have RC core built into kernel.

Thanks @kszaq.

**Pull request merged**
