### PR TITLE
AVL6862 internal dvb driver

### PR DESCRIPTION
**Pull request by afl1**
Add driver for internal dvb tuner based on AVL6862 + R848.

### CODE REVIEW

**Review by Ray-future — APPROVED** [review]
I'm ok with it.  Any objections?

**Comment by kszaq** [comment]
@Raybuntu Please compile-test just in case. Otherwise I'm OK with it.

**Comment by Ray-future** [comment]
Sure I wanned to test it first.

**Comment by chewitt** [comment]
@afl1 will this also support the avl6211 chip? .. I see mention of it in one of the files. If not, could that be taken into account as it's present in a box that I'm working on at the moment. The avl6211 tuner driver files are included in the wetekvb module.

**Comment by afl1** [comment]
No. Driver is for AVL6862 demodulator and R848 tuner only. In dtb for boxes with this tuner  is in section dvbfe  is  'dtv_demod0 = "Avl6211"; '.  It was introduce in dtb before I wrote this driver. I think by @vitmod. I left it to avoid dtb upgrade issue.  There is no conflict with wetek dtb.

**Comment by afl1** [comment]
Is there any issue to merge this PR? Without merging this  I can't continue in LE #2451.

**Comment by Ray-future** [comment]
No issue. I tried and it's building without any issues. I will merge it later if nobody else in the Team objects.

**Pull request merged**
