### PR TITLE
Merge end-of-life lsk-v3.14-16.03-android and v3.14.79

### PR DESCRIPTION
**Pull request by Kwiboo**
This PR merges end-of-life linux-linaro-stable [lsk-v3.14-16.03-android](https://git.linaro.org/kernel/linux-linaro-stable.git/tag/?h=lsk-v3.14-16.03-android) and linux-stable [v3.14.79](http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tag/?h=v3.14.79).

Adds overlayfs, improvements to alsa/usb and lots more.

The merge have been carried out as follow:
- [amlogic-3.14.y](https://github.com/LibreELEC/linux-amlogic/tree/amlogic-3.14.y) include amlogic commits up to b30056ea5874f0dadcc7386a24945559d1139ed6 and is branched from [lsk-v3.14-android-15.01~1](https://github.com/Kwiboo/linux-amlogic/tree/lsk-v3.14-android-15.01~1) (includes v3.14.29)
- [v3.14.79](https://github.com/Kwiboo/linux-amlogic/releases/tag/v3.14.79) was merged on top of [lsk-v3.14-16.03-android](https://github.com/Kwiboo/linux-amlogic/releases/tag/lsk-v3.14-16.03-android) with the result tagged as [lsk-v3.14-16.03-android-v3.14.79](https://github.com/Kwiboo/linux-amlogic/releases/tag/lsk-v3.14-16.03-android-v3.14.79)
- [amlogic-3.14.y](https://github.com/LibreELEC/linux-amlogic/tree/amlogic-3.14.y) was rebased on top of latest amlogic commit b30056ea5874f0dadcc7386a24945559d1139ed6 in the [amlogic-3.14-20161031-rebase](https://github.com/Kwiboo/linux-amlogic/commits/amlogic-3.14-20161031-rebase) branch
- [amlogic-3.14-20161031-rebase](https://github.com/Kwiboo/linux-amlogic/commits/amlogic-3.14-20161031-rebase) was rebased on top of [lsk-v3.14-16.03-android-v3.14.79](https://github.com/Kwiboo/linux-amlogic/releases/tag/lsk-v3.14-16.03-android-v3.14.79) in the [lsk-v3.14-16.03-android-v3.14.79-rebase](https://github.com/Kwiboo/linux-amlogic/commits/lsk-v3.14-16.03-android-v3.14.79-rebase) branch
- [lsk-v3.14-16.03-android-v3.14.79](https://github.com/Kwiboo/linux-amlogic/releases/tag/lsk-v3.14-16.03-android-v3.14.79) was merged on top of [amlogic-3.14.y](https://github.com/LibreELEC/linux-amlogic/tree/amlogic-3.14.y) with all file state reset to same state as the tip of the [lsk-v3.14-16.03-android-v3.14.79-rebase](https://github.com/Kwiboo/linux-amlogic/commits/lsk-v3.14-16.03-android-v3.14.79-rebase) branch
- [lsk-v3.14-android-15.01~1...amlogic-3.14-20161031-rebase](https://github.com/Kwiboo/linux-amlogic/compare/lsk-v3.14-android-15.01~1...amlogic-3.14-20161031-rebase.patch) delta was compared to the [lsk-v3.14-16.03-android-v3.14.79...lsk-v3.14-16.03-android-v3.14.79-rebase](https://github.com/Kwiboo/linux-amlogic/compare/lsk-v3.14-16.03-android-v3.14.79...lsk-v3.14-16.03-android-v3.14.79-rebase.patch) delta

Skipped, empty, superseded or reverted commits:
- empty commit: bcfeb46bc08a Warning: remove of/fdt.c, power/main.c warning
- empty commit: 54fe0e64a0f8 PD#122553: di: add protect for vf_put
- lsk: 118e1bcd485c PD#112280: ipv4: Missing sk_nulls_node_init() in ping_unhash().
- lsk: baa35acaa324 security: lsm_audit: add ioctl specific auditing
- lsk: 008666879a9d SELinux: per-command whitelisting of ioctls
- lsk: fb0b0942afa8 UPSTREAM: KEYS: Fix keyring ref leak in join_session_keyring()
- lsk: 173c1fc4c8fd SELinux: ss: Fix policy write for ioctl operations
- lsk: 322a85565782 PD#120885: cpufreq: interactive: Put global cpufreq kobject on failure
- lsk: 754cc5ea2663 PD#120885: cpufreq: interactive: Don't set floor_validate_time
- lsk: 84606dd81223 PD#120885: cpufreq: interactive: Round up timer_rate to match jiffy
- lsk: 22f56676615c PD#120885: cpufreq: interactive: Exercise hispeed settings
- lsk: dda8556210b4 PD#120885: cpufreq: interactive: Implement cluster-based
- lsk: 60b7629bdbda PD#120885: cpufreq: interactive: Rearm governor timer at max freq
- lsk: d12fff8d42f9 PD#120885: cpufreq_stats: Adds the fucntionality to load
- lsk: 320a34941efa PD#120885: sched: cpufreq: Adds a field cpu_power in the task_struct
- lsk: b76333bcb009 PD#120885: sched: cpufreq: update power usage only if
- lsk: b4ea22b146bd PD#120885: cpufreq: Iterate over all the possible
- lsk: cf893692daca pipe: iovec: Fix memory corruption when retrying atomic copy as non-atomic
- lsk: ec447aa523d7 PD#128865: mm: mmap: add new /proc tunable for mmap_base ASLR
- lsk: 82f8b69394ab PD#128865: arm64: mm: support ARCH_MMAP_RND_BITS
- lsk: b1f231e6a2a0 arm64: el0_dbg does not set link reg for return to user path, breaks debug
- lsk: e29bfa7e619f compiler-gcc: integrate the various compiler-gcc[345].h files
- reverted: 9d175422f14b PD#121425: booting: use async schedule method to save booting time
- revert: 50766a5c28ae Revert "PD#121425: booting: use async schedule method ..."
- incomplete backport: df943434b2c1 PD#128865: mm: expose arch_mmap_rnd when available
- skipped due to #25: 40436644b0e7 PD#118626: tty: merge tty changes from 4.3
- skipped due to #25: 9ef3ff87e31b Revert "PD#118626: tty: merge tty changes from 4.3"

Conflicts:
- 7350cd737357: 498607f8ff3b Warning: remove kernel warning and add warning control
- 7f298032011a: 6e3c93fe0b76 usb: dwc_otg: add usb dwc2 driver
- 95b0bbb2bcf7: 3ec594b31120 PD#105626: usb: gadget: enable adb function
- 2476ed7e974a: d0852118d708 PD#105770: cpufreq: add scaling hotplug governor
- 9b6ec801952a: fbbbfc5b8701 meson8: enable suspend resume function
- 1bcea8ad20b3: 208918b0d8db GXBABY USB driver
- b65df9913d6a: d764f2790e77 Revert "GXBABY USB driver"
- c85697b95880: b328e86796b9 usb: dwc_otg2: initial support gxbb
- 66c2a324884c: 722d79ce3cc8 ethernet: 100M, support gxbb
- 99e26c24f88f: 843c1f7b9e65 sd_emmc: controller optimization for SD3.0 and HS400
- c18fa6d12e2a: 996fc66ac98f mm: optimize CMA for allocation
- d72199e99a37: 4f1c1e375092 PD#105788: thermal: initial support gxbb
- f1e0a492362f: c46f1812238a memtrack: create file in /proc/ion to track memory usage of ION
- af2bfba16ac0: ec0dc776b95c mm:  transplant optimization from 3.10
- b0d8967a339d: 5c63aa95ff75 PD#108319: mm: optimization for low memory
- 31e44ed94ea6: 486242eedc16 PD#110455: net: stmmac: fix oops when resume from standby
- d16339e22ccf: cf8485c63242 PD#111482: clk: add mutex and spin_lock in clk struct
- 38768dfd7d7f: 90227b0b7d77 PD#111994: arm64: Update the Image header
- 3b553e1ff43e: 2eecdc259f19 PD#105950: instaboot: initial support
- 11680c579c4e: 3538b1c46cc4 PD#113106: alarm: prohibit suspend for 2s if alarm comes
- 33b038e9b66b: 653924afc30c PD#113106: alarm: set a timeout wakelock if alarm comes
- 4e950f14c553: 3b1e8281a27e PD#108166: lowmemorykiller: improve the lmk policy
- 746b2be67b03: d96758279118 PD#115026: cpuinfo: add chipid function
- 2715d774a03d: 20bbd205b1ff PD#108166: mm: modify mm stat for memory size mismatch issue
- d574c69f1b01: d7478932a88c PD#115608: arm64: core dump support
- b784a48f4193: 35ba8e670574 PD#117797: devices: remove device_rename function
- d8008d94b90a: bf8d49905b14 PD#114786: coresight: add coresight function for gxbb
- 3f41b2f3e7c1: efbf5e4028cc PD#118612: cortex-a53: fix ARM CPU errata 843419, 845719, 835769
- c5b88a7ab047: 0a83ee1b7d70 PD#122826: cpufreq: don't change cpufreq policy durning cpu hotplug
- 26b5d15cb6ef: 784c1ed9910b PD#128522: cpuidle: support for gxm
- e7b40cd10460: c1c97d693335 PD#129206: mm: optimize cma allocate time
- 81501950d436: 3b1105127799 PD#130385: mm: optimize release time of cma
- cd31acd8e9fa: 5b43fcc0e481 Makefile: Remove some compiler flags that treat warnings as errors to make some drivers build without errors

Review/Notes:
- This is a very large merge and will be very hard to review using only GitHub, `git diff 790d7ab^..790d7ab <path>` is your friend
- `mm/page_alloc.c` could use extra attention as that was the file with most merge conflicts
- [lsk-v3.14.79](https://github.com/LibreELEC/LibreELEC.tv/compare/master...Kwiboo:lsk-v3.14.79) can be used to test this on C2/Hub/Play2

### CODE REVIEW

**Comment by Kwiboo** [comment]
Rebasing on latest amlogic-3.14.y removed one of the merge parents, will push a new update later today.

**Comment by Kwiboo** [comment]
Updated with latest amlogic-3.14.y and correct merge parents this time.

**Comment by lrusak** [comment]
what's the status here?

**Comment by chewitt** [comment]
@codesnake will this PR be superseded with your planned 3.14 kernel über update?

**Comment by Kwiboo** [comment]
I do not think this will be relevant after new amlogic code is merged, I have also switched focus from Amlogic to Rockchip so there is no interest from me to redo a similar rebase/merge.

**Comment by codesnake** [comment]
@chewitt This will not be superseded by planned 3.14 kernel update, because AML kernel is still based on 3.14.29, but the PR may require a rebase.

**Comment by Kwiboo** [comment]
Closing, someone can pick up if there is interest after nougat merge.

**Pull request closed without merging**
