### PR TITLE
Some fixes, reverts and kernel bump

### PR DESCRIPTION
**Pull request by Stane1983**
This reverts drivers/tty commit from Amlogic, removes hotplug governor and bumps kernel to 3.14.79 (mainline). Build is tested against WeTek Hub config, live testing is done on my S905 2Gb device.

### CODE REVIEW

**Comment by lrusak** [comment]
Where does this come from? is it your own work?

**Comment by Stane1983** [comment]
Yep, wrote it some time ago, works with Buildroot builds and LibreELEC master branch. Idea with patch came from @codesnake patch for 3.10 kernel which is not working on 3.14.y. Inspecting boot logs I figured out why it goes to standby.

**Comment by Stane1983** [comment]
Lame, I forgot to switch branches. Sorry about that :)

**Comment by lrusak** [comment]
I'd rather you revert back to the original PR.

If you want to bump the kernel version please open a new PR.

**Comment by chewitt** [comment]
We aren't going to blind merge something that touches ~2k files. I appreciate that some kernel things will touch a large number of files, but PR's need to be reviewable. Please think about how to break this down into multiple digestible changes. Thanks.

**Comment by Stane1983** [comment]
@lrusak @chewitt I will make 2 PRs (original one) and linux version change PR. Changing ~2k files is due to merge v3.14.79 tag from mainline kernel git and I don't have intention to split that in multiple branches (I'm not really sure which rule I should follow to do that). Conflicts that were when merging is because of some things that already existed in Amlogic code (most of it).

**Comment by lrusak** [comment]
The nice thing about git is that you can rebase and force push, this makes it so you don't have to close and reopen PR's anytime you make a mistake.

**Pull request closed without merging**
