### PR TITLE
Change HDMI-Cec OSD name to 'KODI'

### PR DESCRIPTION
**Pull request by yazz007**

### CODE REVIEW

**Comment by kszaq** [comment]
AFAIK OSD name is set in device tree, the change is not needed.

E.g. https://github.com/LibreELEC/linux-amlogic/blob/amlogic-3.14.y/arch/arm64/boot/dts/amlogic/gxbb_p200_1G_wetek_hub.dts#L759

**Review by codesnake — COMMENTED** [review]
I agree with @kszaq, this change is not needed.

**Comment by chewitt** [comment]
@kszaq @codesnake Are there any scenarios where "other" devices don't set a name in device tree and this would apply a better default than Mbox?

**Comment by kszaq** [comment]
If you want to use our kernel you need to use a device tree for our kernel and this value is set in all of them.

**Comment by gdachs** [comment]
This change is wrong! The kernel driver works just fine without Kodi. So why naming it Kodi?

**Comment by chewitt** [comment]
Closing as the consensus is this is not required. Thanks.

**Pull request closed without merging**
