### PR TITLE
[3.14] Merge kernel updates from Amlogic Nougat 2017-09-28 SDK

### PR DESCRIPTION
**Pull request by codesnake**
Merge kernel updates from Amlogic Nougat 2017-09-28 SDK.

### CODE REVIEW

**Comment by codesnake** [comment]
IR key maps for amremote can now be defined in DTS.

Added key map for WeTek Play 2 IR remote.

**Comment by codesnake** [comment]
Fixed Broadcom dhd module loading on WeTek Play 2 by updating the device tree.

**Comment by codesnake** [comment]
I have fixed the VC-1 playback issues. @Raybuntu please check.

**Comment by Ray-future** [comment]
thanks I will

**Comment by kszaq** [comment]
Looks OK on S905X. Great job @codesnake on merging and troubleshooting!

**Pull request merged**
