### PR TITLE
Merge latest updates from upstream Amlogic kernel 3.14

### PR DESCRIPTION
**Pull request by codesnake**
Merge latest updates from upstream Amlogic kernel 3.14 and sync WeTek Hub and WeTek Play 2 device trees according with the updates.

### CODE REVIEW

**Comment by kszaq** [comment]
Looks good to me. :+1:

**Comment by lrusak** [comment]
I'm a little worried about this big of a change before this late in a release. We still probably have at least a month to go but still. Thoughts?

**Comment by wrxtasy** [comment]
I'm going to be a bit Lazy here and ask @codesnake to add this patch for C2 Audio support to this pull request pls.  Tested these Kernel updates on the C2 as well and its good to go 👍 

https://dl.dropboxusercontent.com/u/27641650/WeTek/0001-Odroid_C2-Sync-device-tree-with-gxbb_p200_2G.dts.patch

**Comment by codesnake** [comment]
Added @wrxtasy's patch for Odroid C2.

**Comment by stefansaraev** [comment]
all good so far on wetek play 2.

**Comment by kszaq** [comment]
It's also been working well during my testing on S905/X devices. Also judder issue on interlaced live channels seems to be gone.

**Pull request merged**
