### PR TITLE
drivers/wetek: build open-source dvb driver

### PR DESCRIPTION
**Pull request by afl1**
This PR introduces open-source wetek dvb driver. Module wetekdvb.ko is compiled from source code. Driver was successfully tested in WP2 with CoreELEC 8.90.2 build.

### CODE REVIEW

**Comment by Ray-future** [comment]
Seriously 3 months without even a comment?

**Comment by Ray-future** [comment]
Ground control to Major Tom...

**Comment by lrusak** [comment]
Please be more explicit in the description. What benefits does this provide? Is the patch going upstream? Will it work with the mainline kernel?

Adding patches without a good reason just creates a maintenance nightmare.

**Comment by Ray-future** [comment]
Imo it is best to favor open source drivers than supporting close sourced binary blobs.
I don't know what the plan for LE9 is but I doubt it will be mainline so let me bounce the question back. What is your plan?

**Pull request closed without merging**
